/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const Time = IDL.Int;
export const Review = IDL.Record({
  'customerName' : IDL.Text,
  'date' : Time,
  'comment' : IDL.Text,
  'rating' : IDL.Nat8,
});

export const idlService = IDL.Service({
  'addReview' : IDL.Func([IDL.Text, IDL.Nat8, IDL.Text], [], []),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Time = IDL.Int;
  const Review = IDL.Record({
    'customerName' : IDL.Text,
    'date' : Time,
    'comment' : IDL.Text,
    'rating' : IDL.Nat8,
  });
  
  return IDL.Service({
    'addReview' : IDL.Func([IDL.Text, IDL.Nat8, IDL.Text], [], []),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };